prefix = '>>'
[TOKENS]
bot = ''
idevision = ''
mystbin = ''

[DATABASE]
dsn = 'postgres://pythonistabot:pythonistabot@database:5432/pythonistabot' # assumed default

# 50 = CRITICAL
# 40 = ERROR
# 30 = WARNING
# 20 = INFO
# 10 = DEBUG
[LOGGING]
webhook_url = ""
level = 20

[SNEKBOX] # optional
url = 'http://snekbox:8060' # default url
