prefix = '>>'
owner_ids = [123, 456, 789] # user or role ids, optional

[TOKENS]
bot = ''
idevision = ''  # optional key
mystbin = ''  # optional key
pythonista = ''  # optional key

[DATABASE]
dsn = 'postgres://pythonistabot:pythonistabot@database:5432/pythonistabot' # assumed default

[BADBIN]
domains = ["pastebin.com", "hastebin.com"]

# 50 = CRITICAL
# 40 = ERROR
# 30 = WARNING
# 20 = INFO
# 10 = DEBUG
[LOGGING]
webhook_url = ""  # optional
webhook_avatar_url = "" # optional
level = 20

[SNEKBOX] # optional
url = 'http://snekbox:8060/eval' # default url

[GITHUB] # optional
bot_secret = ""
